spring.application.name=firstModule

# PostgreSQL Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/springboot_db
#spring.datasource.username=postgres
#spring.datasource.password=root

# PostgreSQL Driver
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=create
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
